#ifndef _CLSRVDEF_H_
#define _CLSRVDEF_H_

#define CLSRVDEF_COMMUNICATION_STRING_LEN    2048

#define CLSRVDEF_COMMUNICATION_MESSAGE_LEN CLSRVDEF_COMMUNICATION_STRING_LEN
#define CLSRVDEF_COMMUNICATION_DATA_SIZE   3145728

#define CLSRVDEF_COMMUNICATION_MAXSIZE     CLSRVDEF_COMMUNICATION_DATA_SIZE

#endif
